#!/usr/bin/env node

/**
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const DBMigrate = require('db-migrate');

const ENVS = ['dev', 'test'];

/** Migrates a database for an environment. */
const migrate = (env) => {
  const dbm = DBMigrate.getInstance(true, { env });
  return dbm.up();
};

Promise.all(ENVS.map(migrate));
